### PR TITLE
[Add] bibo: add pre-migration to remove deprecated fields T#54233

### PR DESCRIPTION
**Pull request by agarzaarvizu**
## This MR refers to the task[#54233](https://www.vauxoo.com/web#active_id=54233&cids=1&id=54233&menu_id=&model=project.task)

### CODE REVIEW

**Comment by agarzaarvizu** [comment]
@desdelinux Done


cc @luisg123v

**Comment by desdelinux** [comment]
@agarzaarvizu You can put a more specific message to the commit

**Comment by agarzaarvizu** [comment]
@desdelinux Done

**Comment by desdelinux** [comment]
LGTM

**Pull request merged**
